version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6010:6379
    container_name: redis-dist

  service1:
    build: .
    ports:
      - 6000:3000
      - 16000:5858
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=node-service
      - LOG_TEST_ENV=false
      - NODE_ENV=development
      - EXPOSED_PORT=6000
    container_name: service-dist1
    command: npm run gulp-start

  service2:
    build: .
    ports:
      - 6001:3000
      - 16001:5858
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=node-service
      - LOG_TEST_ENV=false
      - NODE_ENV=development
      - EXPOSED_PORT=6000
    container_name: service-dist2
    command: npm run gulp-start
