version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 7001:6379
    container_name: redis-dist

  service:
    build: .
    ports:
      - 7000:3030
      - 17000:5858
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - SERVICE_NAME=node-service
      - LOG_TEST_ENV=false
      - NODE_ENV=development
      - EXPOSED_PORT=7000
    container_name: node-service-dist
    command: npm run gulp-start

